name: discord_interaction_to_pubsub
description: A Dart server that turns Discord Interactions into PubSub messages.
version: 0.0.0-a1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies: 
  gcloud: ^0.8.8
  shelf: ^1.4.1
  convert: ^3.1.1
  ed25519_edwards: ^0.3.1
  googleapis_auth: ^1.4.1

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.3
  http: ^0.13.6