name: build-and-deploy-to-dockerhub
on:
  push:
    paths: # only run if PR changes are in relevant files
      - 'bin/**'
      - 'lib/**'
      - 'Dockerfile'
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Container image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: enspyrco/discord_interaction_to_pubsub:latest